name: note build
# 触发workflow的条件
on:
  push:
    # 只有master分支发生push事件时，才会触发workflow
    branches: [main]
  pull_request:
    branches: [main]

env:
  SERVER_HOST: ${{ secrets.SERVER_HOST }} # 服务器IP地址
  SERVER_PORT: ${{ secrets.SERVER_PORT }} # 服务器端口
  USER_NAME: ${{ secrets.USER_NAME }} # 服务器用户名
  SERVER_PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }} # 服务器私钥
  cache-name: note

# jobs表示执行的一项或多项任务
jobs:
  build: # 任务的job_id，具体名称自定义，这里build代表打包
    runs-on: ubuntu-latest # runs-on字段指定运行所需要的虚拟机环境。注意：这个是必填字段
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 20
          cache: 'pnpm'
      #缓存依赖
      - name: Get pnpm cache directory path
        id: pnpm-cache-dir-path
        run: echo "dir=$(pnpm store path)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: ${{ env.dir }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      # 装依赖
      - name: Install
        run: pnpm install
      # 打包
      - name: Build
        run: pnpm run docs:build
      # 上传打包资源
      - name: Deploy
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ env.SERVER_PRIVATE_KEY }}
          ARGS: '-avz'
          SOURCE: 'docs/.vuepress/dist/'
          REMOTE_HOST: ${{ env.SERVER_HOST }}
          REMOTE_USER: ${{ env.USER_NAME }}
          REMOTE_PORT: ${{ env.SERVER_PORT }}
          TARGET: /www/wwwroot/doc.yoouu.cn